/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  TouchableHighlight,
  View,
} from 'react-native';
import AudioEditor from 'react-native-audio-editor';
import {useRef} from 'react';

const App = () => {
  const ref = useRef();

  const onConfirm = () => {
    ref.current.onSubmit();
  };

  return (
    <View style={styles.container}>
      <TouchableHighlight>
        <View style={{height: 40, marginTop: 100}}>
          <Text onPress={onConfirm}>asd</Text>
        </View>
      </TouchableHighlight>
      <AudioEditor
        ref={ref}
        audioUri="https://audio.meetyourgenie.com/threads/buoc-qua-nhau-vu-b93ce5c577f7c0b9..mp3"
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

export default App;
